name: 'cloud-init Lint'
description: 'An action for linting cloud-init files'
author: 'AnderssonPeter'
inputs: 
  files:
    description: cloud-init files to scan
    required: false
    default: '**/*cloud-init*.{yml,yaml}'
  ignore:
    description: Files or directories to ignore
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  color: blue
  icon: upload-cloud